# Site settings
title: GPIA GIS
email:
description: > # this means to ignore newlines until "baseurl:"
  This website displays student projects from GPIA GIS.
baseurl: /
url: http://gpia-gis.github.io
twitter_username: TheNewSchool
github_username: gpia-gis

# Build settings
markdown: kramdown
